import { environmentBase } from './environment.base';
import { Environment } from './environment.interface';

/**
 * Docker/Self-hosted environment configuration
 * Used when deploying with docker-compose on Synology NAS or similar
 *
 * This file is auto-generated by: node docker/setup.js <NAS_IP>
 * The setup script will replace the placeholder values below.
 *
 * Features enabled: Profile, Notes, Admin
 * Features disabled: Chat, Files (require Realtime/Storage services)
 */
export const environment: Environment = {
  ...environmentBase,
  production: true,

  supabaseUrl: 'http://YOUR_NAS_IP:8001',
  supabaseAnonKey: 'YOUR_ANON_KEY',

  // No OAuth providers in self-hosted lite setup
  socialProviders: [],

  siteUrl: 'http://YOUR_NAS_IP:4200',

  featureFlags: {
    ...environmentBase.featureFlags,
    // Core features - enabled
    notes: true,
    admin: true,
    breadcrumb: true,
    components: true,

    // Disabled - require additional Supabase services
    chat: false, // Requires Realtime service
    files: false, // Requires Storage service
  },
};
