services:
  # Angular Application
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    container_name: angular-app
    restart: unless-stopped
    ports:
      - '${APP_PORT:-4200}:4200'
    environment:
      NODE_ENV: production
