#!/usr/bin/env node

/**
 * Supabase Lite Setup Script
 *
 * Generates all required secrets and configures the environment for self-hosted deployment.
 *
 * Usage:
 *   node docker/setup.js <nas-ip>
 *
 * Example:
 *   node docker/setup.js 192.168.1.100
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// Parse command line arguments
const args = process.argv.slice(2);
const nasIp = args[0];

if (!nasIp) {
  console.error('Usage: node docker/setup.js <nas-ip>');
  console.error('Example: node docker/setup.js 192.168.1.100');
  process.exit(1);
}

// Validate IP address or hostname format
const ipOrHostnameRegex =
  /^(?:\d{1,3}\.){3}\d{1,3}$|^[a-zA-Z0-9][-a-zA-Z0-9]*(?:\.[a-zA-Z0-9][-a-zA-Z0-9]*)*$/;
if (!ipOrHostnameRegex.test(nasIp)) {
  console.error(`Invalid IP address or hostname: ${nasIp}`);
  process.exit(1);
}

console.log('Supabase Lite Setup');
console.log('===================\n');

// Generate random secrets
function generateSecret(length = 32) {
  return crypto.randomBytes(length).toString('base64').replace(/[+/=]/g, '');
}

// Create a signed JWT
function createJwt(payload, secret) {
  const header = { alg: 'HS256', typ: 'JWT' };

  const base64UrlEncode = (obj) => {
    const json = JSON.stringify(obj);
    const base64 = Buffer.from(json).toString('base64');
    return base64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
  };

  const headerEncoded = base64UrlEncode(header);
  const payloadEncoded = base64UrlEncode(payload);
  const signatureInput = `${headerEncoded}.${payloadEncoded}`;

  const signature = crypto
    .createHmac('sha256', secret)
    .update(signatureInput)
    .digest('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');

  return `${headerEncoded}.${payloadEncoded}.${signature}`;
}

// Generate secrets
const postgresPassword = generateSecret(32);
const jwtSecret = generateSecret(48); // Longer for JWT

// JWT payload timestamps (valid for ~6 years)
const iat = Math.floor(Date.now() / 1000);
const exp = iat + 200000000; // ~6 years

// Generate API keys
const anonKey = createJwt({ role: 'anon', iss: 'supabase', iat, exp }, jwtSecret);
const serviceRoleKey = createJwt({ role: 'service_role', iss: 'supabase', iat, exp }, jwtSecret);

console.log('Generated secrets:');
console.log(`  POSTGRES_PASSWORD: ${postgresPassword.substring(0, 10)}...`);
console.log(`  JWT_SECRET: ${jwtSecret.substring(0, 10)}...`);
console.log(`  ANON_KEY: ${anonKey.substring(0, 30)}...`);
console.log(`  SERVICE_ROLE_KEY: ${serviceRoleKey.substring(0, 30)}...`);
console.log('');

// Determine file paths
const scriptDir = __dirname;
const projectRoot = path.dirname(scriptDir);

const envPath = path.join(scriptDir, '.env');
const envDockerPath = path.join(projectRoot, 'src', 'environments', 'environment.docker.ts');

// Create .env file
const envContent = `# Supabase Lite - Generated Configuration
# Generated by setup.js on ${new Date().toISOString()}
# Target: ${nasIp}

# =============================================================================
# SECRETS (auto-generated)
# =============================================================================

POSTGRES_PASSWORD=${postgresPassword}
JWT_SECRET=${jwtSecret}
ANON_KEY=${anonKey}
SERVICE_ROLE_KEY=${serviceRoleKey}

# =============================================================================
# URLs
# =============================================================================

SITE_URL=http://${nasIp}:4200
API_EXTERNAL_URL=http://${nasIp}:8001

# =============================================================================
# PORTS
# =============================================================================

KONG_HTTP_PORT=8001
APP_PORT=4200

# =============================================================================
# AUTH OPTIONS
# =============================================================================

DISABLE_SIGNUP=false
MAILER_AUTOCONFIRM=true
JWT_EXPIRY=3600
SMTP_ADMIN_EMAIL=admin@localhost
`;

fs.writeFileSync(envPath, envContent);
console.log(`Created: ${envPath}`);

// Update environment.docker.ts
const envDockerContent = `import { environmentBase } from './environment.base';
import { Environment } from './environment.interface';

/**
 * Docker/Self-hosted environment configuration
 * Used when deploying with docker-compose on Synology NAS or similar
 *
 * Generated by: node docker/setup.js ${nasIp}
 * Generated on: ${new Date().toISOString()}
 *
 * Features enabled: Profile, Notes, Admin
 * Features disabled: Chat, Files (require Realtime/Storage services)
 */
export const environment: Environment = {
  ...environmentBase,
  production: true,

  supabaseUrl: 'http://${nasIp}:8001',
  supabaseAnonKey:
    '${anonKey}',

  // No OAuth providers in self-hosted lite setup
  socialProviders: [],

  siteUrl: 'http://${nasIp}:4200',

  featureFlags: {
    ...environmentBase.featureFlags,
    // Core features - enabled
    notes: true,
    admin: true,
    breadcrumb: true,
    components: true,

    // Disabled - require additional Supabase services
    chat: false, // Requires Realtime service
    files: false, // Requires Storage service
  },
};
`;

fs.writeFileSync(envDockerPath, envDockerContent);
console.log(`Updated: ${envDockerPath}`);

// Update kong.yml with actual API keys (Kong doesn't auto-substitute env vars)
const kongPath = path.join(scriptDir, 'volumes', 'kong', 'kong.yml');
if (fs.existsSync(kongPath)) {
  let kongContent = fs.readFileSync(kongPath, 'utf8');

  // Replace placeholders with actual keys
  kongContent = kongContent.replace(/\$\{SUPABASE_ANON_KEY\}/g, anonKey);
  kongContent = kongContent.replace(/\$\{SUPABASE_SERVICE_KEY\}/g, serviceRoleKey);

  // Also handle if keys were previously substituted (for re-runs)
  // Match JWT pattern: eyJ...base64...
  kongContent = kongContent.replace(
    /(username: ANON[\s\S]*?keyauth_credentials:[\s\S]*?-\s*key:\s*)(eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)/,
    `$1${anonKey}`,
  );
  kongContent = kongContent.replace(
    /(username: SERVICE[\s\S]*?keyauth_credentials:[\s\S]*?-\s*key:\s*)(eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)/,
    `$1${serviceRoleKey}`,
  );

  fs.writeFileSync(kongPath, kongContent);
  console.log(`Updated: ${kongPath}`);
}

console.log('\n' + '='.repeat(60));
console.log('Setup complete!');
console.log('='.repeat(60));
console.log(`
Next steps:

1. Copy files to your NAS:
   scp -r . user@${nasIp}:/volume1/docker/angular-starter/

2. SSH into your NAS and start services:
   ssh user@${nasIp}
   cd /volume1/docker/angular-starter/docker
   docker-compose up -d

3. Open http://${nasIp}:4200 and register
   The first registered user automatically becomes admin.

For troubleshooting, see: docs/self-hosted-setup.md
`);
