export { AuthService } from './auth';
export type { SocialProvider } from './auth';
export { authGuard, guestGuard } from './auth-guard';
export { roleGuard } from './role-guard';
export type { UserRole } from './role-guard';
export { SupabaseService } from './supabase';
export { SUPABASE_ERRORS } from './supabase-errors';
export { PreferencesService, COLOR_THEMES } from './preferences';
export type { ColorTheme } from './preferences';
export { GlobalErrorHandler } from './global-error-handler';
export { httpErrorInterceptor } from './http-error-interceptor';
export { mapError, mapToError, unwrap, unwrapWithCount } from './error-mapper';
export { extractErrorMessage } from './extract-error-message';
export { RealtimeService } from './realtime';
export type { ConnectionStatus, RealtimeEventType, RealtimePayload } from './realtime';
export { StorageService } from './storage';
export { unsavedChangesGuard } from './unsaved-changes-guard';
export type { HasUnsavedChanges } from './unsaved-changes-guard';
export { FeatureFlags } from './feature-flags';
export { featureFlagGuard } from './feature-flag-guard';
